### ISSUE TITLE
Enable direct installation without conda

### ISSUE THREAD

**Issue by luator** [open-dynamic-robot-initiative/trifinger_simulation#57]
So far the standalone installation of this package depends on conda because that was the only way to get pinocchio in a pure-Python setup.  This changed now, as [pinocchio is now on pypi](https://github.com/stack-of-tasks/pinocchio/issues/1317#issuecomment-836584355).  This means all dependencies can now be installed via pip alone.

To make the usage of this package easier, I therefore propose to get rid of the conda-stuff and instead use pip only (of course conda users could still install it in conda using pip, it would just not be a requirement anymore to use conda).

I'm not sure what exactly is needed for this, but assume that we just need to specify the dependencies correctly inside the setup.py.

Steps:

- [x] Change setup scripts so that trifinger_simulation can be pip-installed properly (including all dependencies).
- [x] Update documentation
- [ ] ~Remove the conda-related files?~
- [x] Maybe even put trifinger_simulation on pypi?

**Comment by giadefa** [comment]
the pin installation on pip is not compatible with CentOS7 due to newer glibc

**Comment by luator** [comment]
> the pin installation on pip is not compatible with CentOS7 due to newer glibc

Oh, that's unfortunate.  Did you test if installing it via conda works?
In any case, I think it would be good to report this to the Pinocchio maintainers.

**Comment by luator** [comment]
trifinger_simulation is now on PyPI :tada:
https://pypi.org/project/trifinger-simulation/
